name: Bogosort Runner

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bogosort:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Fix git ownership
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Run bogosort
        run: node bogosort.js

      - name: Generate SVG
        run: node generate-status-svg.js

      - name: Update README with status
        run: node update-readme.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add bogosort-status.svg README.md bogosort-status.json
          git commit -m "Bogosort update" || echo "No changes"
          git pull --rebase
          git push || echo "Push failed"
